"""add receipt fields

Revision ID: f0469f6edf33
Revises: 
Create Date: 2026-01-24 16:30:57.091657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0469f6edf33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('raw_text', sa.String(length=15000), nullable=True))
    op.alter_column('receipts', 'total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_transactions_source_job_id_import_jobs'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'source_job_id')
    op.drop_column('user_merchant_preferences', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_merchant_preferences', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('transactions', sa.Column('source_job_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_transactions_source_job_id_import_jobs'), 'transactions', 'import_jobs', ['source_job_id'], ['id'])
    op.alter_column('receipts', 'total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_column('receipts', 'raw_text')
    # ### end Alembic commands ###
